#default site with leaflet added using jekyll new site

# Site settings
title: Intro to Leaflet & Jekyll
email: mmeyer@ovrdc.org
description: "This repo contains examples from the presentation at the Northeast Ohio GIS Symposium on Leaflet, Jekyll and TurfJS.
To view the examples, either run jekyll serve, or just view the html files in the _sites folder. You will want to view these with Firefox if you are not running a local web server."
baseurl: "https://ovrdc.github.io/neohio-gis-2016-leaflet-jekyll-turf" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: getbounds
github_username:  ovrdc

# Build settings
markdown: kramdown
highlighter: rouge

include: ["_pages"]
output_ext: html
permalink: /:title.html

#Define default layout and categories to make this a bit easier for my map example posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "map"
      category: "examples"
      permalink: /:title.html
